In [ ]:
def cal_c_f(e_c,em_f):
  return e_c * em_f

In [ ]:
e_c = 1000
em_f = 0.475

carbon_footprint = cal_c_f(e_c,em_f)
print(f"carbon footprint: {carbon_footprint}kg CO2")

carbon footprint: 475.0kg CO2


In [ ]:
cities = [
    {"name": "mysore","carbon_footprint":500},
    {"name": "chennai","carbon_footprint":350},
    {"name": "mangalore","carbon_footprint":600},
    {"name": "bangalore","carbon_footprint":200},
]

sustainabilty_threshold = 400
sustainabilty_cities = list(filter(lambda city: city["carbon_footprint"] < sustainabilty_threshold,cities))

print("sustainabilty_cities")
for city in sustainabilty_cities:
  print(f"{city['name']}: {city['carbon_footprint']}kg CO2")

sustainabilty_cities
chennai: 350kg CO2
bangalore: 200kg CO2


In [ ]:
class Person:
  def __init__(self,name,age):
    self.name = name
    self.age = age


In [ ]:
person = Person("john",30)
person.name
person.age

30

In [ ]:
class car:
    wheels = 4

    def __init__(self,make,year):
        self.make = make
        self.year = year

    def start_engine(self):
        print("engine started")

    @classmethod
    def get_wheels(cls):
        return cls.wheels

    @staticmethod
    def is_motor_vechile():
        return True

In [ ]:
Car = car("Toyota",2020)
print(Car.make)
print(Car.year)

Toyota
2020


In [ ]:
Car.start_engine()

engine started


In [ ]:
Car.get_wheels()

4

In [ ]:
Car.is_motor_vechile()

True

In [ ]:
car.is_motor_vechile()

True

In [ ]:
class Person:
  def __init__(self,name,age):
    self._name = name
    self._age = age

  def name(self):
    return self._name

In [ ]:
person = Person("nikhil",21)
person._name

'nikhil'

In [ ]:
class Person:
  def __init__(self,name,age):
    self.__name = name
    self.__age = age

  def name(self):
    return self.__name

In [ ]:
person = Person("nikhil",21)
person.name()

'nikhil'

In [ ]:
person = Person("nikhil",21)
person._Person__name

'nikhil'

In [ ]:
class vechile:
    def __init__(self,brand,model):
        self.brand = brand
        self.model = model

    def display_info(self):
        return f"{self.brand} {self.model}"

class car(vechile):
    def __init__(self,brand,model,doors):
        super().__init__(brand,model)
        self.doors = doors

    def info(self):
        return f"{self.brand} {self.model} {self.doors}"

In [ ]:
my_car = car("Toyota","supra",4)
my_car.info()

'Toyota supra 4'

In [ ]:
class Animal:
  def make_sound(self):
    print("animal sound")

class Dog(Animal):
  def make_sound(self):
    print("bark")

In [ ]:
op = Dog()
op.make_sound()

bark


In [ ]:
class Example:
  def sum(self,*args):
    return sum(args)

In [ ]:
obj = Example()
obj.sum(1,2,3,4,5)

15

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
renewable_sources = ['solar','wind','hydro','geothermal','tidal']

rs = pd.Series(renewable_sources)
rs

0         solar
1          wind
2         hydro
3    geothermal
4         tidal
dtype: object

In [ ]:
data = {
    'project':['solar farm','wind turbine','hydro plant','geothermal station','tidal plant'],
    'technology':['solar','wind','hydro','geothermal','tidal'],
    'capacity(MW)':[150,300,200,50,175],
    'cost(Million $)':[200,400,350,100,250],
    'location':['California','Texas','Washington','Nevada','Los Angelas'],
    'YOC':[2023,2022,2021,2023,2022]
}

df = pd.DataFrame(data)
df

project  technology  capacity(MW)  cost(Million $)     location  \
0          solar farm       solar           150              200   California   
1        wind turbine        wind           300              400        Texas   
2         hydro plant       hydro           200              350   Washington   
3  geothermal station  geothermal            50              100       Nevada   
4         tidal plant       tidal           175              250  Los Angelas   

    YOC  
0  2023  
1  2022  
2  2021  
3  2023  
4  2022

In [ ]:
df.columns

Index(['project', 'technology', 'capacity(MW)', 'cost(Million $)', 'location',
       'YOC'],
      dtype='object')

In [ ]:
df['project']

0            solar farm
1          wind turbine
2           hydro plant
3    geothermal station
4           tidal plant
Name: project, dtype: object

In [ ]:
df['YOC']

0    2023
1    2022
2    2021
3    2023
4    2022
Name: YOC, dtype: int64

In [ ]:
#filtering
high_capacity= df[df['capacity(MW)'] > 150]
high_capacity

project technology  capacity(MW)  cost(Million $)     location   YOC
1  wind turbine       wind           300              400        Texas  2022
2   hydro plant      hydro           200              350   Washington  2021
4   tidal plant      tidal           175              250  Los Angelas  2022

In [ ]:
high_cost = df[df['cost(Million $)'] > 200]
high_cost

project technology  capacity(MW)  cost(Million $)     location   YOC
1  wind turbine       wind           300              400        Texas  2022
2   hydro plant      hydro           200              350   Washington  2021
4   tidal plant      tidal           175              250  Los Angelas  2022

In [ ]:
#cost per MW
df['Cosr per MW']=df['cost(Million $)']/df['capacity(MW)']
df

project  technology  capacity(MW)  cost(Million $)     location  \
0          solar farm       solar           150              200   California   
1        wind turbine        wind           300              400        Texas   
2         hydro plant       hydro           200              350   Washington   
3  geothermal station  geothermal            50              100       Nevada   
4         tidal plant       tidal           175              250  Los Angelas   

    YOC  Cosr per MW  
0  2023     1.333333  
1  2022     1.333333  
2  2021     1.750000  
3  2023     2.000000  
4  2022     1.428571

In [ ]:
#aggregation
total_cost = df['cost(Million $)'].sum()
total_capacity = df['capacity(MW)'].sum()
print(f"total cost: {total_cost} million dollars and total capacity: {total_capacity} MW")

total cost: 1300 million dollars and total capacity: 875 MW


In [ ]:
#group by
grouped_data = df.groupby('technology')['capacity(MW)'].sum()
grouped_data

technology
geothermal     50
hydro         200
solar         150
tidal         175
wind          300
Name: capacity(MW), dtype: int64

In [ ]:
a = np.array([1,2])
a

array([1, 2])

In [ ]:
a.ndim

1

In [ ]:
b = np.array([[1,2,4],[2,4,6]])
b

array([[1, 2, 4],
       [2, 4, 6]])

In [ ]:
c = np.array([[[9, 10, 11], [12, 13, 14]],
              [[15, 16, 17], [18, 19, 20]],
              [[21, 22, 23], [24, 25, 26]]])
c

array([[[ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [ ]:
c.ndim

4

In [ ]:
z = np.random.randn(5)
z

array([-0.29251899,  1.35677139,  0.51612818, -1.01715141, -0.55644427])

In [ ]:
y = np.random.rand(3,3)
y

array([[0.48870267, 0.38670302, 0.72753026],
       [0.44450629, 0.5840577 , 0.55652198],
       [0.45347116, 0.192686  , 0.18582828]])

In [ ]:
p = np.random.randint(0,10,size=(3,3))
p

array([[8, 4, 5],
       [1, 1, 7],
       [1, 7, 6]])

In [ ]:
q = np.random.choice(5,3)
q

array([2, 2, 1])

In [ ]:
w = np.random.choice(5,5,replace=False)
w

array([2, 1, 0, 4, 3])